[package]
name = "cmakeperf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used to parse and produce full-build CSV profiles
csv = "1.1"

# Used to notify of unexpected clang output
log = "0.4"

# Used to parse the CMake compilation database
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shlex = "1.1"

# Used to monitor available RAM and command RAM usage
sysinfo = "0.26"

# Used to generate error types with reasonable boilerplate
thiserror = "1.0"

# Used to monitor and cancel build processes
wait-timeout = "0.2"
