[package]
name = "crofiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang-time-trace = { git = "https://github.com/HadrienG2/clang-time-trace.git" }
cpparser = { git = "https://github.com/HadrienG2/cpparser.git" }
once_cell = "1.10"
termion = "1.5"
unicode-segmentation = "1.9"
unicode-width = "0.1"

# Easier profiling
[profile.release]
debug = 2