[workspace]
members = ["dispplay", "simpp"]

[package]
name = "crofiler"
version = "0.1.0"
edition = "2021"

[features]
# Display statistics on the usage of the C++ entity interners
#
# This can be used during development to adjust interner key sizes based on
# real-world workloads.
#
unstable_interner_stats = []

# Check for absence of panics in TUI-exercised code paths
#
# Panics from the TUI have a terrible user experience, the application just
# stops with no indication of what went wrong. We use dtolnay's no_panic crate
# to check that no panic occurs.
#
no_panic = ["no-panic"]

[dependencies]
atty = "0.2"
chrono = "0.4"
clang-time-trace = { path = "clang-time-trace" }
clap = { version = "3.2", features = ["derive"] }
csv = "1.1"
cursive = { version = "0.20", default-features = false, features = ["termion-backend"] }
cursive_table_view = "0.14"
decorum = "0.3"
env_logger = "0.9"
log = "0.4"
no-panic = { version = "0.1", optional = true }
once_cell = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shlex = "1.1"
syslog = "6.0"
termion = "1.5"
termtree = "0.4"
thiserror = "1.0"
unicode-segmentation = "1.9"
unicode-width = "0.1"

[dev-dependencies]
assert_matches = "1.5"

[profile.release]
debug = 1  # Needed for profiling

[profile.bench]
debug = 1  # Needed for profiling
codegen-units = 1  # Needed for inlining decision determinism