[workspace]
members = ["simpp"]

[package]
name = "crofiler"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"
chrono = "0.4"
clang-time-trace = { path = "clang-time-trace" }
clap = { version = "3.2", features = ["derive"] }
cursive = { version = "0.18", default-features = false, features = ["termion-backend"] }
cursive_table_view = "0.14"
env_logger = "0.9"
once_cell = "1.10"
scoped_threadpool = "0.1"
termion = "1.5"
termtree = "0.4"
thiserror = "1.0"
unicode-segmentation = "1.9"
unicode-width = "0.1"

[dev-dependencies]
assert_matches = "1.5"

[profile.release]
debug = 1  # Needed for profiling

[profile.bench]
debug = 1  # Needed for profiling
codegen-units = 1  # Needed for inlining decision determinism