[workspace]
members = ["simpp"]

[package]
name = "crofiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clang-time-trace = { path = "clang-time-trace" }
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.9"
once_cell = "1.10"
termion = "1.5"
termtree = "0.4"
unicode-segmentation = "1.9"
unicode-width = "0.1"

[profile.release]
debug = 1  # Needed for profiling

[profile.bench]
debug = 1  # Needed for profiling
codegen-units = 1  # Needed for inlining decision determinism