[package]
name = "crofiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang-time-trace = { git = "https://github.com/HadrienG2/clang-time-trace.git" }
once_cell = "1.10"
termion = "1.5"
unicode-segmentation = "1.9"
unicode-width = "0.1"

# TODO: Remove after integrating c++ entity parting into clang-time-trace
unicode-xid = "0.2"
nom = "7.1"
nom-supreme = "0.8"
[dev-dependencies]
pretty_assertions = "1.2"

[profile.release]
debug = 2