[package]
name = "clang-time-trace"
version = "0.1.0"
edition = "2021"

[dependencies]
cpp_demangle = "0.3"
cpparser = { path = "../cpparser" }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5"
maplit = "1.0"
more-asserts = "0.2"
pretty_assertions = "1.2"
