[package]
name = "simpp"
version.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive", "wrap_help"] }
cpparser = { path = "../cpparser" }
